# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e4516474944bf50661b1d4bbaed17f03cb6a43b2ddaf1d30754039f383b256173a7e8f1d9465692647f28eb80cc535a6c36d605b748134a4a94319393d3477c

test:
  secret_key_base: 347c0f82948d6eafa536fa87a8189bdf29a364bb8a65fb614eaa7698818077286002def4c836907c400081365c4008d640879581431274578e41aaf194381ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
